In [6]:
import pandas as pd

df = pd.read_csv('data/Fish.csv')
df

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [7]:
df['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [34]:
fish_input = df[['Weight', 'Length2', 'Length3', 'Height', 'Width']]
fish_input.head()

Weight  Length2  Length3   Height   Width
0   242.0     25.4     30.0  11.5200  4.0200
1   290.0     26.3     31.2  12.4800  4.3056
2   340.0     26.5     31.1  12.3778  4.6961
3   363.0     29.0     33.5  12.7300  4.4555
4   430.0     29.0     34.0  12.4440  5.1340

In [35]:
fish_target = df[['Species']]

In [36]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = \
train_test_split(fish_input, fish_target)

In [37]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [38]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier()
kn.fit(train_scaled, train_target)

print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.8571428571428571
0.75


C:\Users\1-16\Desktop\DAMF22\ML\venv\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [39]:
kn.predict(test_scaled)

array(['Bream', 'Smelt', 'Perch', 'Pike', 'Perch', 'Bream', 'Bream',
       'Pike', 'Perch', 'Perch', 'Smelt', 'Parkki', 'Perch', 'Perch',
       'Bream', 'Bream', 'Bream', 'Whitefish', 'Perch', 'Perch', 'Smelt',
       'Perch', 'Perch', 'Perch', 'Whitefish', 'Perch', 'Perch', 'Pike',
       'Smelt', 'Roach', 'Perch', 'Parkki', 'Smelt', 'Parkki', 'Pike',
       'Roach', 'Perch', 'Pike', 'Perch', 'Perch'], dtype=object)

In [40]:
kn.predict_proba(test_scaled)

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0.8, 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0.4, 0.6, 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0.2, 0.4, 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0.8, 0. , 0. , 0. , 0.2],
       [0. , 0. , 0.4, 0. , 0.2, 0. , 0.4],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0.8, 0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.8, 0.2, 0. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.2, 0.2, 0. , 0. , 0.2, 0. , 0.4],
       [0. , 0. , 0.6, 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0.6, 0. , 0.2, 0. , 0.2],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0.6, 0.4, 0. , 0. , 0. ],
       [0. , 0. , 0.6, 0. , 0.2,

## 로지스틱 회귀
- 그래프가 0과 1에 수렴하지 않음

In [15]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')

train_bs = train_scaled[bream_smelt_indexes['Species']]
target_bs = train_target[bream_smelt_indexes['Species']]
target_bs

Species
157   Smelt
29    Bream
18    Bream
31    Bream
150   Smelt
17    Bream
11    Bream
33    Bream
20    Bream
22    Bream
27    Bream
32    Bream
153   Smelt
147   Smelt
156   Smelt
152   Smelt
23    Bream
28    Bream
26    Bream
145   Smelt
9     Bream
10    Bream
146   Smelt
154   Smelt
16    Bream
3     Bream
24    Bream
15    Bream
14    Bream
5     Bream
34    Bream
151   Smelt
21    Bream
148   Smelt
149   Smelt
155   Smelt
19    Bream
12    Bream
6     Bream
4     Bream
158   Smelt

In [41]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bs, target_bs)

lr.predict(train_bs[:5])
lr.predict_proba(train_bs[:5]).round(3) # 소수점 줄이기

C:\Users\1-16\Desktop\DAMF22\ML\venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0.052, 0.948],
       [0.999, 0.001],
       [0.99 , 0.01 ],
       [0.999, 0.001],
       [0.022, 0.978]])

In [44]:
# 소프트맥스 함수로 감싸기 전
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision, decimals=2))

NameError: name 'np' is not defined

In [24]:
lr.coef_

array([[-0.52537004, -0.63483682, -0.70791532, -0.98627142, -0.77578168]])

In [29]:
lr = LogisticRegression(C=20, max_iter=1000) # 최적으로 만들어내기
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))
      

0.907563025210084
0.925


C:\Users\1-16\Desktop\DAMF22\ML\venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [30]:
lr.predict_proba(test_scaled[:5]).round(3)

array([[0.   , 0.015, 0.776, 0.   , 0.078, 0.127, 0.004],
       [0.352, 0.574, 0.   , 0.   , 0.039, 0.   , 0.034],
       [0.997, 0.   , 0.   , 0.   , 0.   , 0.   , 0.003],
       [0.   , 0.004, 0.741, 0.002, 0.229, 0.003, 0.021],
       [0.032, 0.001, 0.374, 0.028, 0.209, 0.   , 0.356]])

In [31]:
print(lr.classes_)

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']


In [33]:
lr.coef_.shape

(7, 5)

- 로지스틱 회귀: 숫자를 z값 만들어내는 역할
- 다중분류일때는 확률의 합이 1이 넘는 오류 발생
- 소프트맥스 함수 사용 -> 여러개의 데이터의 비율을 일정하게 나눠서 전체 비율이 1이 넘지 않도록 조정